#!/bin/bash

echo "🚀 DT extras - Development Environment Ready!"
echo "============================================="
echo ""
echo "📋 Available Commands:"
echo "  ./scripts/start-services.sh    - Start both backend and frontend"
echo "  ./scripts/start-backend.sh     - Start backend only"
echo "  ./scripts/start-frontend.sh    - Start frontend only"
echo "  ./scripts/stop-services.sh     - Stop all services"
echo ""
echo "🔗 Service URLs:"
echo "  Backend API:     http://localhost:8000"
echo "  API Docs:        http://localhost:8000/docs"
echo "  Frontend:        http://localhost:5173"
echo "  DT API:          http://localhost:8081"
echo "  DT Frontend:     http://localhost:8080"
echo ""
echo "💡 Quick Start:"
echo "  1. Run './scripts/start-services.sh' to start everything"
echo "  2. Open http://localhost:5173 in your browser"
echo "  3. Use './scripts/stop-services.sh' to stop everything"
echo ""
echo "📁 Project Structure:"
echo "  backend/     - FastAPI backend"
echo "  frontend/    - Vue.js frontend"
echo "  api/         - YAML taxonomy storage"
echo "  scripts/     - Startup and utility scripts"
echo ""
echo "✨ Development environment is ready!"
