name: "Release"

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  workflow_dispatch:
  workflow_call:

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
      packages: write
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "Login to Container registry"
        uses: "docker/login-action@v3"
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build and push backend image"
        id: backend_build
        uses: "docker/build-push-action@v7"
        with:
          context: ./backend
          push: true
          tags: ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: "Build and push frontend image"
        id: frontend_build
        uses: "docker/build-push-action@v7"
        with:
          context: ./frontend
          push: true
          tags: ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

      - name: "Generate Backend SBOM"
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}
          format: cyclonedx-json
          artifact-name: backend-sbom-cdx.json

      - name: "Generate frontend SBOM"
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }}
          format: cyclonedx-json
          artifact-name: frontend-sbom-cdx.json

      - name: Get previous tag
        id: previousTag
        run: |
          name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
          echo "previousTag: $name"
          echo "previousTag=$name" >> $GITHUB_ENV

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ env.previousTag }}
          writeToFile: false

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          makeLatest: {{is_default_branch}}
          name: ${{ github.ref_name }}
          # in the body, show both the changes and the reference to the backend and frontend images
          body: |
            ${{ steps.changelog.outputs.changes }}

            ## Images

            - Backend: ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}
            - Frontend: ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
